# Generated by Django 5.1.7 on 2025-04-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bankaccount_businessprofile_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(choices=[('ecocash', 'EcoCash'), ('CBZ bank', 'cbz bank'), ('NMB Bank', 'nmb bank'), ('visa', 'visa')], default='EcoCash', max_length=100),
        ),
    ]
